spring:
  application:
    name: mople
  profiles:
    active: dev
  batch:
    job:
      enabled: false
  cloud:
    openfeign:
      client:
        config:
          tmdb:
            connect-timeout: 3000
            read-timeout: 10000
            # (주의)full로 올리면 Authorization 헤더에 tmdb api가 로그에 남아 유출됨
            logger-level: basic
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  kafka:
    topics:
      follow-created: mople.follow.created.v1
      playlist-content-added: mople.playlist.content-added.v1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retries: 3
        retry.backoff.ms: 1000
        retry.backoff.max.ms: 4000
    consumer:
      group-id: mople
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.codeit.mople.domain.*"

server:
  port: 8080
  shutdown: graceful

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  access-token-expiration: 1800000     # 30분 (ms)
  refresh-token-expiration: 604800000  # 7일 (ms)

password-reset:
  expiration-minutes: 3

admin:
  email: "admin@mople.com"
  password: ${ADMIN_PASSWORD}
  name: "관리자"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
external-api:
  tmdb:
    image-base-url: https://image.tmdb.org/t/p/w500

batch:
  tmdb:
    collect:
      max-pages: 5
      skip-limit: 10