spring:
  application:
    name: mople
  profiles:
    active: dev
  batch:
    job:
      enabled: false
  cloud:
    openfeign:
      client:
        config:
          tmdb:
            connect-timeout: 3000
            read-timeout: 10000
            logger-level: basic

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  access-token-expiration: 1800000     # 30분 (ms)
  refresh-token-expiration: 604800000  # 7일 (ms)

password-reset:
  expiration-minutes: 3

admin:
  email: "admin@mople.com"
  password: ${ADMIN_PASSWORD}
  name: "관리자"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
external-api:
  tmdb:
    image-base-url: https://image.tmdb.org/t/p/w500

batch:
  tmdb:
    collect:
      max-pages: 5